name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
        cache: 'pip'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        pip install openai>=1.0.0 nicegui>=1.2.0 PyQt5>=5.15.0 pydantic>=2.10.6 uvicorn>=0.34.0 \
                    fastapi>=0.115.8 click>=8.1.8 slowapi>=0.1.9 tiktoken>=0.8.0 dnspython>=2.7.0 \
                    email-validator>=2.2.0 llama_index==0.12.*
    
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: false
        load: true
        tags: app:test
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Test with Docker
      run: |
        docker run app:test python -m pytest